- hosts: all
  become: true
  tasks:
    - name: Delete old Deployment and Service
      command:
        chdir: '/home/ubuntu/{{JOB_NAME}}'
        cmd: 'kubectl delete -f Deployment.yml -f Service.yml'

    - name: Create new Deployment and Service
      command:
        chdir: '/home/ubuntu/{{JOB_NAME}}'
        cmd: 'kubectl apply -f Deployment.yml -f Service.yml'
