- hosts: all
  become: true
  tasks:
    - name: Delete old Deployment and Service
      command: 'kubectl delete -f /home/ubuntu/"{{ JOB_NAME }}"/Deployment.yml -f /home/ubuntu/"{{ JOB_NAME }}"/Service.yml'
    - name: Create new Deployment and Service
      command: 'kubectl apply -f /home/ubuntu/"{{ JOB_NAME }}"/Deployment.yml -f /home/ubuntu/"{{ JOB_NAME }}"/Service.yml'
