apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
  labels:
    app: web-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels:
        app: web-page
    spec:
      containers:
      - name: web-page
        image: veenlorivz/kubernetes-project:latest
        imagePullPolicy: always
        ports:
        - containerPort: 80
