apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    name: web-page
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31200
